sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jm987/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jm987/react-test npm test

after_success:
  - docker build -t jm987/multi-client./client
  - docker build -t jm987/multi-nginx ./nginx
  - docker build -t jm987/multi-server ./server
  - docker build -t jm987/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jm987/multi-client
  - docker push jm987/multi-nginx
  - docker push jm987/multi-server
  - docker push jm987/multi-worker
